#!/usr/bin/env bash
# Script to configure web-02 to be identical to web-01
apt-get -y update
apt-get -y install nginx
sudo chmod 777 /var/www/html -R
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo chmod 777 etc/nginx/sites-available/default
CUS_NAME="server_name _;\n\tadd_header X-Served-By $HOSTNAME;"
sed -i "s/server_name _;/$CUS_NAME/" /etc/nginx/sites-available/default
service nginx restart
