#!/usr/bin/env bash
# A Bash script that gives you information about the school file.
# if the file exists: school file exists
# if the file does not exist: school file does not exist
# If the file exists, print:
# if the file is empty: school file is empty
# if the file is not empty: school file is not empty
# if the file is a regular file: school is a regular file
# if the file is not a regular file: (nothing)

if [ -e "holbertonschool" ]
then
echo "holbertonschool file exists"
if [ -s "holbertonschool" ]
then
echo "holbertonschool file is not empty"
else
echo "holbertonschool file is empty"
fi
if [ -f "holbertonschool" ]
then
echo "holbertonschool is a regular file"
fi
else
echo "holbertonschool file does not exist"
fi