#!/usr/bin/env bash
# script that changes NGINX user and privilages
pkill apache2
sed -i "s/user www-data;/user nginx;/" /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo chown nginx /etc/nginx/nginx.conf
sudo chgrp nginx /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
